[package]
name = "implot-sys-bindgen"
version = "0.3.0"
authors = ["Sandro Merkli"]
edition = "2018"

[dependencies]
bindgen = "0.57"
imgui-sys = { git = "https://github.com/syndelis/imgui-rs", branch = "fix/alpha-blending", features = ["docking"] }

