[package]
name = "implot-sys-bindgen"
version = "0.3.0"
authors = ["Sandro Merkli"]
edition = "2018"

[dependencies]
bindgen = "0.57"
imgui-sys = { git = "https://github.com/imgui-rs/imgui-rs.git", rev = "fef6509a6e2bae62e1c30a46d3a4eaa0d7a83ddb" }
